-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 19:32:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema silicon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema silicon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `silicon` DEFAULT CHARACTER SET utf8mb3 ;
USE `silicon` ;

-- -----------------------------------------------------
-- Table `silicon`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`alumno` (
  `Cod_matricula` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_matricula`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`automovil` (
  `Id_automovil` INT NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Precio_hora` FLOAT NOT NULL,
  `Cant_combustible` FLOAT NOT NULL,
  PRIMARY KEY (`Id_automovil`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`clientes` (
  `Id_cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT NOT NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`curso` (
  `Cod_curso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `alumno_Cod_matricula` INT NOT NULL,
  PRIMARY KEY (`Cod_curso`, `alumno_Cod_matricula`),
  INDEX `fk_curso_alumno1_idx` (`alumno_Cod_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_curso_alumno1`
    FOREIGN KEY (`alumno_Cod_matricula`)
    REFERENCES `silicon`.`alumno` (`Cod_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`profesor` (
  `Id_profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Especialidad` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_profesor`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`curso_has_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`curso_has_profesor` (
  `curso_Cod_curso` INT NOT NULL,
  `curso_alumno_Cod_matricula` INT NOT NULL,
  `profesor_Id_profesor` INT NOT NULL,
  PRIMARY KEY (`curso_Cod_curso`, `curso_alumno_Cod_matricula`, `profesor_Id_profesor`),
  INDEX `fk_curso_has_profesor_profesor1_idx` (`profesor_Id_profesor` ASC) VISIBLE,
  INDEX `fk_curso_has_profesor_curso1_idx` (`curso_Cod_curso` ASC, `curso_alumno_Cod_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_curso_has_profesor_curso1`
    FOREIGN KEY (`curso_Cod_curso`)
    REFERENCES `silicon`.`curso` (`Cod_curso`),
  CONSTRAINT `fk_curso_has_profesor_profesor1`
    FOREIGN KEY (`profesor_Id_profesor`)
    REFERENCES `silicon`.`profesor` (`Id_profesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`pais` (
  `Id_pais` INT NOT NULL AUTO_INCREMENT,
  `Nombre_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`provincia` (
  `Id_provincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre_provincia` VARCHAR(45) NOT NULL,
  `pais_Id_pais` INT NOT NULL,
  PRIMARY KEY (`Id_provincia`, `pais_Id_pais`),
  INDEX `fk_provincia_pais1_idx` (`pais_Id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_provincia_pais1`
    FOREIGN KEY (`pais_Id_pais`)
    REFERENCES `silicon`.`pais` (`Id_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`localidad` (
  `Cod_localidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Cod_postal` INT NOT NULL,
  `provincia_Id_provincia` INT NOT NULL,
  `provincia_pais_Id_pais` INT NOT NULL,
  PRIMARY KEY (`Cod_localidad`, `provincia_Id_provincia`, `provincia_pais_Id_pais`),
  INDEX `fk_localidad_provincia1_idx` (`provincia_Id_provincia` ASC, `provincia_pais_Id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_localidad_provincia1`
    FOREIGN KEY (`provincia_Id_provincia` , `provincia_pais_Id_pais`)
    REFERENCES `silicon`.`provincia` (`Id_provincia` , `pais_Id_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`empleado` (
  `Id_empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `F_alta` DATE NOT NULL,
  `localidad_Cod_localidad` INT NOT NULL,
  `localidad_provincia_Id_provincia` INT NOT NULL,
  `localidad_provincia_pais_Id_pais` INT NOT NULL,
  PRIMARY KEY (`Id_empleado`, `localidad_Cod_localidad`, `localidad_provincia_Id_provincia`, `localidad_provincia_pais_Id_pais`),
  INDEX `fk_empleado_localidad1_idx` (`localidad_Cod_localidad` ASC, `localidad_provincia_Id_provincia` ASC, `localidad_provincia_pais_Id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_localidad1`
    FOREIGN KEY (`localidad_Cod_localidad` , `localidad_provincia_Id_provincia` , `localidad_provincia_pais_Id_pais`)
    REFERENCES `silicon`.`localidad` (`Cod_localidad` , `provincia_Id_provincia` , `provincia_pais_Id_pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`reservas` (
  `Id_reservas` INT NOT NULL AUTO_INCREMENT,
  `F_inicio` DATE NOT NULL,
  `F_final` DATE NOT NULL,
  `Precio_total` FLOAT NOT NULL,
  `clientes_Id_cliente` INT NOT NULL,
  PRIMARY KEY (`Id_reservas`, `clientes_Id_cliente`),
  INDEX `fk_reservas_clientes1_idx` (`clientes_Id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_clientes1`
    FOREIGN KEY (`clientes_Id_cliente`)
    REFERENCES `silicon`.`clientes` (`Id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `silicon`.`reservas_has_automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silicon`.`reservas_has_automovil` (
  `reservas_Id_reservas` INT NOT NULL,
  `reservas_clientes_Id_cliente` INT NOT NULL,
  `automovil_Id_automovil` INT NOT NULL,
  PRIMARY KEY (`reservas_Id_reservas`, `reservas_clientes_Id_cliente`, `automovil_Id_automovil`),
  INDEX `fk_reservas_has_automovil_automovil1_idx` (`automovil_Id_automovil` ASC) VISIBLE,
  INDEX `fk_reservas_has_automovil_reservas1_idx` (`reservas_Id_reservas` ASC, `reservas_clientes_Id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_has_automovil_automovil1`
    FOREIGN KEY (`automovil_Id_automovil`)
    REFERENCES `silicon`.`automovil` (`Id_automovil`),
  CONSTRAINT `fk_reservas_has_automovil_reservas1`
    FOREIGN KEY (`reservas_Id_reservas` , `reservas_clientes_Id_cliente`)
    REFERENCES `silicon`.`reservas` (`Id_reservas` , `clientes_Id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
